/**
 * Public-repo stub — typings/data/resource.ts
 *
 * In the full system this file is generated by Amplify codegen
 * (`amplify/data/resource.ts` → `a.schema({ … })`).  The real Schema
 * carries deep generic metadata that drives `generateClient<Schema>()`
 * to produce a fully-typed data client.  Replicating that here is
 * impractical, so we export `any` to keep the runner readable.
 *
 * Models in the production schema:
 *   Conversation, Memory, Workflow, WorkflowAccess,
 *   WorkflowProgress, Collection, BasePromptVersion,
 *   ActivePromptPointer, ModelCircuitBreaker, AuditLog
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Schema = any;
